logging.level:
  com.podbox: INFO
  com.hazelcast: INFO
  com.hazelcast.cluster: DEBUG
  org.springframework: WARN

spring:
  profiles.active: local
  output.ansi.enabled: always
  main:
    banner-mode: "off"
    web-environment: false
